# Generated by Django 4.0.3 on 2022-03-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcomp', '0003_alter_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='name_human_readable',
            field=models.CharField(default='Aula közepe', max_length=50),
            preserve_default=False,
        ),
    ]
